### ISSUE TITLE
v3 pg707 ex4.13 could remind reader that z = f(x,y) here

### ISSUE THREAD

**Issue by cbm755** [APEXCalculus/APEXCalculus_Source#4]
I think it should say `$z = f(x, y) = \sqrt{x} \sin y$`.  Without `f(x,y)` its confusing for someone skimming.

(just started looking at your book, like what I see so far!)

**Comment by APEXCalculus** [comment]
Colin,
 Thanks for the suggestion. I'll think about it. I see your point; when z
values are determined by a function of x and y, we don't automatically know
that this function is named "f." Explicitly stating this relationship has
its benefits, and one could argue that technically, without it, the text is
"wrong."

This has ramifications throughout the book. I did a cursory check and the
same issue appears in the two sections following. I would suspect that in
the single variable portion of the book, I define things like " y  = x^2 "
then ask "What is f'(x)?" Addressing this issue consistently would take a
careful reading of the text. I won't argue for not making a change "because
it would take too long", but I don't want to fix some wording in one
section and ignore all other places it occurs.

One reason I avoided language like this from the start is that I think
students find it distracting/confusing. Perhaps if I consistently used the
notation, they would learn to understand what it means, but I was concerned
that the extra notation would bog them down.

I do appreciate the suggestion, and I will be giving it some thought. The
next revision of the text is tentatively scheduled for Spring/Summer '17
(ready for new adoptions in the fall), so I have some time to think about
it and implement change.

Take care.

Greg

**Comment by cbm755** [comment]
Thanks for the detailed response.  I see your point.

I'll have to look back at my notes but I suspect in my teaching (currently from Stewart but...) I tend to talk a lot about `f(x, y)` and rather take the `z =` part for granted.  This probably creates its own form of confusion; I will also try to think about it more this autumn.

I don't think I write down `\partial z / \partial x` very often but I write `\partial f / \partial x` a lot.
